/**
 * The AI coach orchestrator: serve from cache when the numbers haven't moved,
 * otherwise assemble the input, ask Foundry, validate, sanitise, store. Also
 * the only place that spends money, so the cost guards live here:
 *
 *   - TTL per (person, range); a soft TTL skips even the hash check
 *   - Regenerate: ≥ 10 min apart per key, ≤ 120 generations/hour globally
 *   - single-flight per key (two tabs → one call)
 *   - no activity → canned "nothing to coach on" without a provider call
 *   - provider failure with a cached row → serve it, flagged stale
 */
import {
  MIN_RECOMMENDATIONS,
  sanitizeRecommendations,
  stableStringify,
  type RecommendationInput,
  type RecommendationsPayload,
  type RecommendationsResponse,
} from '@dash/shared';
import type { FastifyBaseLogger } from 'fastify';
import type { AiConfig } from '../env';
import type { Repos } from '../repos';
import { FoundryCoach, AiUpstreamError, type GenerationUsage } from '../ai/foundryClient';
import { SYSTEM_PROMPT } from '../ai/prompt';
import { RECOMMENDATIONS_JSON_SCHEMA, parsePayload } from '../ai/recommendationSchema';
import { nowIso } from '../util/time';
import { buildRecommendationInputForUser, type AssembledInput } from './recommendationInput';
import type { RangeParams } from './scoring';

export { AiUpstreamError };

export class RateLimitedError extends Error {
  constructor(public readonly retryAfterSec: number) {
    super(`regenerate is rate-limited; try again in ${Math.ceil(retryAfterSec / 60)} min`);
    this.name = 'RateLimitedError';
  }
}

const REGEN_MIN_INTERVAL_MS = 10 * 60_000;
const GLOBAL_MAX_PER_HOUR = 120;
const RETENTION_DAYS = 30;

type Logger = Pick<FastifyBaseLogger, 'info' | 'warn' | 'error'>;

const consoleLog: Logger = {
  // eslint-disable-next-line no-console
  info: (...a: unknown[]) => console.log('[ai-coach]', ...a),
  // eslint-disable-next-line no-console
  warn: (...a: unknown[]) => console.warn('[ai-coach]', ...a),
  // eslint-disable-next-line no-console
  error: (...a: unknown[]) => console.error('[ai-coach]', ...a),
} as unknown as Logger;

export class RecommendationService {
  private readonly coach: FoundryCoach;
  private log: Logger = consoleLog;
  private readonly inflight = new Map<string, Promise<RecommendationsResponse>>();
  private readonly lastForcedAt = new Map<string, number>();
  private readonly generatedAt: number[] = [];

  constructor(
    private readonly repos: Repos,
    private readonly cfg: AiConfig,
  ) {
    this.coach = new FoundryCoach(cfg);
  }

  setLogger(log: Logger): void {
    this.log = log;
  }

  get model(): string {
    return this.cfg.model;
  }

  get disclosure(): string {
    return `Generated by Claude on Microsoft Foundry (${this.cfg.model}) from the numbers on this page only — never from prompts, code or file names. Cached up to ${this.cfg.ttlHours}h.`;
  }

  async getOrGenerate(userId: number, range: RangeParams, opts: { force: boolean }): Promise<RecommendationsResponse> {
    const key = `${userId}:${range.from}_${range.to}`;
    const running = this.inflight.get(key);
    if (running && !opts.force) return running;
    const p = this.run(userId, range, opts.force, key).finally(() => this.inflight.delete(key));
    this.inflight.set(key, p);
    return p;
  }

  private async run(userId: number, range: RangeParams, force: boolean, key: string): Promise<RecommendationsResponse> {
    const rangeKey = `${range.from}_${range.to}`;
    const row = this.repos.aiRecs.get(userId, rangeKey);
    const ttlMs = this.cfg.ttlHours * 3_600_000;
    const softTtlMs = ttlMs / 4;
    const age = row ? Date.now() - Date.parse(row.generated_at) : Infinity;

    if (row && !force && age < softTtlMs) return this.fromRow(row, true, null);

    let assembled: AssembledInput | null = null;
    if (row && !force && age < ttlMs) {
      assembled = buildRecommendationInputForUser(this.repos, userId, range);
      if (assembled && assembled.hash === row.input_hash) return this.fromRow(row, true, null);
    }

    if (force) this.checkRegenerateBudget(key);
    assembled ??= buildRecommendationInputForUser(this.repos, userId, range);
    if (!assembled) throw new AiUpstreamError(404, 'user_not_found');
    const { input, hash } = assembled;

    // Nothing happened in this range: say so without paying for a model call.
    if (input.activity.sessions === 0) {
      return this.store(userId, rangeKey, input, hash, cannedNoActivity(input), null, 'none');
    }

    const started = Date.now();
    try {
      const gen = await this.coach.generateJson(SYSTEM_PROMPT, stableStringify(input), RECOMMENDATIONS_JSON_SCHEMA as unknown as Record<string, unknown>);
      const payload = sanitizeRecommendations(parsePayload(gen.json), input);
      if (!payload.dataThin && payload.recommendations.length < MIN_RECOMMENDATIONS) {
        throw new AiUpstreamError(502, `only ${payload.recommendations.length} usable recommendations came back`);
      }
      this.noteGenerated(key, force);
      this.log.info(
        {
          userId,
          rangeKey,
          structured: gen.structured,
          attempts: gen.attempts,
          usage: gen.usage,
          ms: Date.now() - started,
          recommendations: payload.recommendations.length,
        },
        'ai coach: generated',
      );
      return this.store(userId, rangeKey, input, hash, payload, gen.usage, gen.model);
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err);
      this.log.warn({ userId, rangeKey, err: message, ms: Date.now() - started }, 'ai coach: generation failed');
      if (row) return this.fromRow(row, true, `Could not refresh: ${message}`);
      if (err instanceof AiUpstreamError) throw err;
      throw new AiUpstreamError(502, message);
    }
  }

  private checkRegenerateBudget(key: string): void {
    const now = Date.now();
    const last = this.lastForcedAt.get(key);
    if (last !== undefined && now - last < REGEN_MIN_INTERVAL_MS) {
      throw new RateLimitedError(Math.ceil((REGEN_MIN_INTERVAL_MS - (now - last)) / 1000));
    }
    while (this.generatedAt.length > 0 && now - (this.generatedAt[0] ?? now) > 3_600_000) this.generatedAt.shift();
    if (this.generatedAt.length >= GLOBAL_MAX_PER_HOUR) {
      throw new RateLimitedError(Math.ceil((3_600_000 - (now - (this.generatedAt[0] ?? now))) / 1000));
    }
  }

  private noteGenerated(key: string, forced: boolean): void {
    const now = Date.now();
    this.generatedAt.push(now);
    if (forced) this.lastForcedAt.set(key, now);
  }

  private store(
    userId: number,
    rangeKey: string,
    input: RecommendationInput,
    hash: string,
    payload: RecommendationsPayload,
    usage: GenerationUsage | null,
    model: string,
  ): RecommendationsResponse {
    const generatedAt = nowIso();
    this.repos.aiRecs.upsert({
      user_id: userId,
      range_key: rangeKey,
      generated_at: generatedAt,
      model,
      input_hash: hash,
      input_json: JSON.stringify(input),
      output_json: JSON.stringify(payload),
      usage_json: usage ? JSON.stringify(usage) : null,
    });
    this.repos.aiRecs.pruneOlderThan(RETENTION_DAYS);
    return this.response(userId, rangeKey, payload, input, generatedAt, model, hash, false, null);
  }

  private fromRow(row: { user_id: number; range_key: string; generated_at: string; model: string; input_hash: string; input_json: string; output_json: string }, cached: boolean, staleReason: string | null): RecommendationsResponse {
    const payload = JSON.parse(row.output_json) as RecommendationsPayload;
    const input = JSON.parse(row.input_json) as RecommendationInput;
    return this.response(row.user_id, row.range_key, payload, input, row.generated_at, row.model, row.input_hash, cached, staleReason);
  }

  private response(
    userId: number,
    rangeKey: string,
    payload: RecommendationsPayload,
    input: RecommendationInput,
    generatedAt: string,
    model: string,
    inputHash: string,
    cached: boolean,
    staleReason: string | null,
  ): RecommendationsResponse {
    const [from = '', to = ''] = rangeKey.split('_');
    return {
      ...payload,
      userId,
      range: { from, to },
      generatedAt,
      model: model === 'none' ? this.cfg.model : model,
      cached,
      inputHash,
      staleReason,
      disclosure: this.disclosure,
      input,
    };
  }
}

function cannedNoActivity(input: RecommendationInput): RecommendationsPayload {
  return {
    standing: `No Claude Code sessions were recorded for you between ${input.range.from} and ${input.range.to}, so there is nothing to coach on in this range yet.`,
    dataThin: true,
    strengths: [],
    recommendations: [
      {
        id: 'start-with-one-task-a-day',
        title: 'Start with one task a day',
        why: `Sessions in this range: ${input.activity.sessions}. The scores only begin to mean something after ${3} active days.`,
        tryThis: 'Pick one small, well-defined task each day this week — a test, a refactor, a bug — and run it end to end in Claude Code.',
        expectedEffect: { axis: 'adoption', note: 'active days and sessions are 80% of the Adoption score' },
        evidence: ['activity.sessions', 'activity.activeDays', 'targets.sessions'],
      },
    ],
  };
}
